wandb_version: 1

dataset:
  desc: null
  value: Breast Cancer
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.5
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1718183208.0
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.10.12
      5: 0.16.5
      8:
      - 1
      - 2
      - 3
      - 5
      13: windows-amd64
